repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        name: ruff lint
        args: [--fix]
      - id: ruff-format
        name: ruff format
  - repo: local
    hooks:
      - id: pytest
        name: pytest unit tests
        entry: uv run pytest tests/unit/
        language: system
        pass_filenames: false
        always_run: true