name: Deploy Documentation

on:
  workflow_dispatch:  # Allow manual triggering from GitHub Actions tab
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'pyproject.toml'
      - 'src/**'

jobs:
  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Verify Fly CLI
        run: |
          which fly || (echo "fly command not found in PATH" && exit 1)
          fly version
      
      - name: Deploy to Fly.io
        run: |
          cd docs
          bash deploy.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
